name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-awesome-pages-plugin
      
      - name: Build site
        run: mkdocs build

      - name: Patch index.html with correct search worker
        run: |
          python <<EOF
          import re
          from pathlib import Path

          site_dir = Path("site")
          worker_dir = site_dir / "assets" / "javascripts" / "workers"
          index_file = site_dir / "index.html"

          try:
              worker_file = next(worker_dir.glob("search.*.min.js"))
              html = index_file.read_text()

              html = re.sub(
                  r'"search":\s*"(?:/)?assets/javascripts/workers/search\.[^"]+\.min\.js"',
                  f'"search": "/assets/javascripts/workers/{worker_file.name}"',
                  html
              )

              index_file.write_text(html)
              print(f"✅ Patched index.html with search worker: {worker_file.name}")
          except Exception as e:
              print(f"⚠️ Failed to patch index.html: {e}")
          EOF

      - name: Deploy site
        run: mkdocs gh-deploy --force
